### PR TITLE
Adding back rspec files for code review

### PR DESCRIPTION
**Pull request by adriaanbd**

### CODE REVIEW

**Review by heyapricot — CHANGES_REQUESTED** [review]
# Let's use *let*
In the same fashion as your enumerables specs please use let o these test cases (And any test case you create from now on). Thanks!

**Comment by mcrd25** [comment]
@heyapricot  Used let statement as seen in commit [fe1ab259f51fd87376f64b9acd0494cc5e5dc2f8](https://github.com/adriaanbd/tic-tac-toe/commit/fe1ab259f51fd87376f64b9acd0494cc5e5dc2f8) where feasible. Not all cases it was necessary.

Thanks a lot for your advice. I believe using let would help improve our tests as well as we can stick to a few variables and reuse them instead of making up new values each time.

Hope this is the close of this chapter. Thanks a lot for your really good code reviews in this project.

👍

**Comment by heyapricot** [comment]
I'm just curious about why you didn't decide to use `let(:board) { Board.new(...) }`. But yes, we can close this chapter

**Comment by mcrd25** [comment]
Just something overlooked in the moment. 😅

**Review by heyapricot — APPROVED** [review]
# *Let*'s 🚢 it
No need from my side for further review. Let's move to the next project

**Pull request merged**
